In [2]:
import numpy as np


### Initial parameters
weights=np.array([[0.1,0.2,0.3,0.4],
                [0.5,0.6,0.7,0.8],
                [0.9,1.0,1.1,1.2]])
bias=np.array([0.1,0.2,0.3])
inputs=np.array([1,2,3,4])

learning_rate=0.001


def relu(x):
    return(np.maximum(0,x))


def relu_derivative(x):
    return np.where(x>0,1.,0.)

for iterations in range(200):
    # forward pass
    z=np.dot(weights,inputs)+bias
    a=relu(z)
    y=np.sum(a)
    loss=y**2


    #backward pass
    dl_dy=2*y
    dy_da=np.ones_like(a)

    dL_da=dl_dy*dy_da
    da_dz=relu_derivative(z)

    dL_dz=dL_da*da_dz


    dL_dw=np.outer(dL_dz,inputs)

    dL_db=dL_dz


    ##update weights and biases
    weights-=learning_rate*dL_dw
    bias-=learning_rate*dL_db

    ## print the loss for every 20 iteration
    if iterations%20==0:
        print(f"iteration{iterations+1},loss:{loss}")


print('final weights:\n',weights)
print('final bias:\n',bias)

iteration1,loss:466.56000000000006
iteration21,loss:5.32959636083938
iteration41,loss:0.41191523404899866
iteration61,loss:0.031836212079467595
iteration81,loss:0.002460565465389601
iteration101,loss:0.000190172825660145
iteration121,loss:1.4698126966451542e-05
iteration141,loss:1.1359926717815175e-06
iteration161,loss:8.779889800154524e-08
iteration181,loss:6.7858241357822796e-09
final weights:
 [[-0.00698895 -0.01397789 -0.02096684 -0.02795579]
 [ 0.25975286  0.11950572 -0.02074143 -0.16098857]
 [ 0.53548461  0.27096922  0.00645383 -0.25806156]]
final bias:
 [-0.00698895 -0.04024714 -0.06451539]
